FROM docker.io/nvidia/cuda:13.0.1-base-ubuntu24.04

ENV DEBIAN_FRONTEND=noninteractive PIP_PREFER_BINARY=1
ARG COMFYUI_TAG=v0.3.59
ENV ROOT=/comfyui

RUN set -eux \
    && apt-get update \
    && apt-get install -y --no-install-recommends git python3.12 python3.12-venv python3-pip libgl1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 仮想環境作成
ENV VENV_PATH=/opt/venv
RUN python3 -m venv $VENV_PATH
ENV PATH="${VENV_PATH}/bin:${PATH}"

RUN --mount=type=cache,target=/root/.cache/pip \
    set -eux \
    && git clone https://github.com/comfyanonymous/ComfyUI.git ${ROOT} \
    && cd ${ROOT} \
    && git checkout tags/${COMFYUI_TAG} \
    && sed -i 's/^torch$/torch==2.7.1/' requirements.txt \
    && pip3 install --upgrade pip \
    && pip3 install -r requirements.txt

WORKDIR ${ROOT}
COPY . /docker/
RUN chmod u+x /docker/entrypoint.sh \
    && cp /docker/extra_model_paths.yaml ${ROOT}

#RUN bash /docker/patch_weights_only.sh

ENV NVIDIA_VISIBLE_DEVICES=all PYTHONPATH="${PYTHONPATH}:${PWD}" CLI_ARGS=""
EXPOSE 8888
ENTRYPOINT ["/docker/entrypoint.sh"]
CMD python -u main.py --listen --port 8888 ${CLI_ARGS}
